### ISSUE TITLE
The actual Chromium implementation of SimHash is slightly different

### ISSUE THREAD

**Issue by letalvoj** [hybridtheory/floc-simhash#3]
It should be noted here, that the actual chromium implementation differs in a way that instead of averaging bits of the hashes it samples values from a gaussian distribution, initialized _using the hashes_ and averages them.

https://github.com/chromium/chromium/blob/c4d3c31083a2e1481253ff2d24298a1dfe19c754/components/federated_learning/sim_hash.cc#L54-L91

I tried to do some comparison and statistically, the two implementations seems to behave identically. I do not actually understand hashing / cryptography enough to understand, why the extra step is needed.

**Comment by ber2** [comment]
Hi @letalvoj, sorry it has taken me a bit to get back to you.
Indeed, this algorithm was developed when the chromium implementation was still a whitepaper, so we put together a SimHash implementation that might differ in some details.

Regarding the selection of random unit vectors, [this](https://stackoverflow.com/questions/6283080/random-unit-vector-in-multi-dimensional-space) discussion pretty much explains why it is fine to sample vector coordinates from a Gaussian and then normalize.
